services:
    digipolis_syslog.processor.client_ip:
        class: DigipolisGent\SyslogBundle\Monolog\Processor\ClientIpProcessor
        arguments: [ "@request_stack" ]
        tags:
            - { name: monolog.processor }

    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags:
            - { name: monolog.processor }

    digipolis_syslog.processor.timestamp:
        class: DigipolisGent\SyslogBundle\Monolog\Processor\TimestampProcessor
        tags:
            - { name: monolog.processor }

    digipolis_syslog.processor.base_url:
        class: DigipolisGent\SyslogBundle\Monolog\Processor\BaseUrlProcessor
        arguments: [ "@request_stack" ]
        tags:
            - { name: monolog.processor }

    digipolis_syslog.processor.uid:
        class: DigipolisGent\SyslogBundle\Monolog\Processor\UidProcessor
        arguments: [ "@security.token_storage" ]
        tags:
            - { name: monolog.processor }

    digipolis_syslog.processor.lowercase_level:
        class: DigipolisGent\SyslogBundle\Monolog\Processor\LowerCaseLevelNameProcessor
        tags:
            - { name: monolog.processor }

    monolog.formatter.kibana:
        class: Monolog\Formatter\LineFormatter
        arguments:
            # %base_url%|%timestamp%|%type%|%severity%|%ip%|%request_uri%|%referer%|%uid%|%link%|%message%
            format: "%%extra.base_url%%|%%timestamp%%|symfony|%%level_name%%|%%extra.client_ip%%|%%extra.base_url%%%%extra.url%%|%%extra.referrer%%|%%extra.uid%%||%%message%%"
